server {
    listen 80;
    listen 443 ssl;
    server_name localhost;

    # SSL Certificates
    ssl_certificate /etc/nginx/cert.crt;
    ssl_certificate_key /etc/nginx/cert.key;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # SPA fallback routing
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend internally
    location /api/ {
        proxy_pass http://finance_backend:3000/api/;
    }
}
